version: '3.9'

services:
  db:
    image: postgres:14.16
    container_name: max_log_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./config/.env.prod
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    container_name: max_log_web
    volumes:
      - static_volume:/home/max_log/web/static
      - media_volume:/home/max_log/web/media
    expose:
      - 8000
    env_file:
      - ./config/.env.prod
    depends_on:
      - redis
      - db
  nginx:
    build: ./nginx
    restart: always
    container_name: max_log_nginx
    volumes:
      - static_volume:/home/max_log/web/static
      - media_volume:/home/max_log/web/media
    ports:
      - 8000:80
    depends_on:
      - web
  redis:
    image: redis:latest
    container_name: max_log_redis
    volumes:
      - redisdata:/data

volumes:
  postgres_data:
  static_volume:
  media_volume:
  redisdata:
