# Generated by Django 5.2.14 on 2026-09-07 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('step', models.CharField(blank=True, max_length=32)),
                ('needs_action', models.BooleanField(default=False)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Посетитель',
                'verbose_name_plural': 'Посетители',
            },
        ),
        migrations.CreateModel(
            name='VisitorLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=32)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='core.visitor')),
            ],
            options={
                'verbose_name': 'Запись лога',
                'verbose_name_plural': 'Записи лога',
                'ordering': ['created_at'],
            },
        ),
    ]
