# Generated by Django 5.2.14 on 2026-09-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_visitor_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='country',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
