# Generated by Django 5.2.14 on 2026-09-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='document',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_registered',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='slug',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Phone number'),
        ),
    ]
